name: 'Run Checkly MaC Checks'
on: [deployment_status]
env:
  ENVIRONMENT_URL: ${{ github.event.deployment_status.environment_url }}
  CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
  CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
  GITHUB_CONTEXT: ${{ toJson(github) }}
jobs:
  test-e2e:
    if: github.event.deployment_status.state == 'success' && contains(github.event.deployment_status.environment_url, 'checklyhq-')
    name: Test E2E on Checkly
    runs-on: ubuntu-latest
    environment:
      name: staging
    timeout-minutes: 10
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.event.deployment_status.deployment.ref }}"
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        # GH actions runs NPM 6. Somehow NPM CI fails with Cannot read property 'babel-core' of undefined
        run: npm install --no-save
      - name: Validate checkly config
        run: npm run checkly:deploy -- --preview
      - name: Run checks
        id: run-checks
        run: npm run checkly:test --
          -e ENVIRONMENT_URL=${{ env.ENVIRONMENT_URL }}
      - id: create-summary
        run: cat checkly-github-report.md > $GITHUB_STEP_SUMMARY
      - id: print-github-event-context
        run: |
          echo "$GITHUB_CONTEXT"
      - id: post-comment-summary
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.workflow_run.pull_requests[0].number }}
          header: Checkly Run Summary ${{ github.event.workflow_run.pull_requests[0].number }} ${{ github.event.number }} -
          path: checkly-github-report.md
          hide_and_recreate: true
          hide_classify: "OUTDATED"
      - name: Deploy checks
        if: steps.run-checks.outcome == 'success' && github.event.deployment_status.environment == 'Production'
        run: npm run checkly:deploy
